services:
    api:
        ports:
            - "8001:8000"
        volumes:
            - ./api:/code
        env_file: .env_dev
        deploy:
            resources:
                limits:
                    memory: 3G
        # networks:
        #     - inditan_dev

    postgres:
        ports:
            - "9802:5432"
        restart: always
        volumes:
          - /dbpool/ubuntu/db_data/:/data
        deploy:
          resources:
            limits:
              memory: 2G
        # networks:
        #     - inditan_dev

    website:
        ports:
            - "8101:8000"
        volumes:    
            - ./web:/code
        env_file: .env_dev
        deploy:
            resources:
                limits:
                    memory: 3G
        # networks:
        #     - inditan_dev
    # beat:
    #     volumes:
    #         - ./api:/code
    #     env_file: .env_dev

    # worker:
    #     volumes:
    #         - ./api:/code
    #     env_file: .env_dev
    #     restart: always
# networks:
#     inditan_dev:
#         driver: overlay