version: '3'
services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.django
    postgres:
        build:
            context: ./api
            dockerfile: Dockerfile.postgres