version: '3'
services:
  api:
    image: deploy-api
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-secure.entrypoints=websecure"
      - "traefik.http.routers.api-secure.rule=Host(`inditan.com`) && PathPrefix(`/api/v1/`)"
      - "traefik.http.routers.api-secure.tls.certresolver=myresolver" 
      - "traefik.http.routers.api-secure.middlewares=security-headers@file"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 6G
    healthcheck:
      test: curl --fail http://localhost:8000/api/v1/admin/ || exit 1 
      interval: 30s  
      retries: 10 
      # start_interval: 30s 
      start_period: 30m  
      timeout: 5s 
    networks:
      - inditan_prod 
    stop_grace_period: 30s
networks: 
  inditan_prod:
    external: true    
    driver: overlay                      