services:
    traefik:
        image: traefik:v3.0
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./traefik:/etc/traefik" 
            - "./letsencrypt:/letsencrypt"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.dashboard.entrypoints=websecure"
            - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
            - "traefik.http.routers.dashboard.service=api@internal"
            - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
        networks:
            - prod
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    memory: 2G

    api:
        volumes:
            - static:/code/static
        env_file: .env
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api-secure.entrypoints=websecure"
            - "traefik.http.routers.api-secure.rule=Host(`localhost`) && PathPrefix(`/api/v1/`)"
            - "traefik.http.routers.api-secure.tls.certresolver=myresolver"
        deploy:
            mode: replicated
            replicas: 3


        deploy:
            mode: replicated
            replicas: 1
            resources:
              limits:
                memory: 3G
        healthcheck:
            test: curl --fail http://localhost:8000/api/v1/admin/ || exit 1
            interval: 30s
            retries: 10
              # start_interval: 30s
            start_period: 30m
            timeout: 5s
        networks:
            - prod
        stop_grace_period: 30s

    worker:
        env_file: .env
        restart: always
        deploy:
            mode: replicated
            replicas: 3

    beat:
        env_file: .env

    website:
        build:
            context: ./website
            dockerfile: Dockerfile.django
        volumes:
            - static:/static
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.website.entrypoints=web"
            - "traefik.http.routers.website.middlewares=redirect-to-https@file"
            - "traefik.http.routers.website.rule=Host(`localhost`)"
            - "traefik.http.routers.website-secure.entrypoints=websecure"
            - "traefik.http.routers.website-secure.rule=Host(`localhost`)"
            - "traefik.http.routers.website-secure.tls.certresolver=myresolver"
            - "traefik.http.routers.static-secure.entrypoints=websecure"
            - "traefik.http.routers.static-secure.rule=Host(`localhost`) && PathPrefix(`/api/v1/static/`)"
            - "traefik.http.routers.static-secure.tls.certresolver=myresolver"
        networks:
            - prod
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    memory: 2G