services:
    api:
        ports:
            - "8001:8000"
        volumes:
            - ./api:/code
        env_file: .env_dev
        deploy:
            resources:
                limits:
                    memory: 3G
    postgres:
        ports:
            - "9803:5432"
        restart: always
        volumes:
          - ../ecommerce_data:/data
        deploy:
          resources:
            limits:
              memory: 2G
    website:
        ports:
            - "8101:8000"
        volumes:    
            - ./web:/code
        env_file: .env_dev
        deploy:
            resources:
                limits:
                    memory: 3G
    redis:
        container_name: redis
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - ../redis_data:/data
    beat:
        volumes:
            - ./api:/code
        env_file: .env_dev
        depends_on:
            - redis
            - api
            - worker
    worker:
        volumes:
            - ./api:/code
        env_file: .env_dev
        restart: always
        depends_on:
            - redis