services:
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.django

    postgres:
        build:
            context: ./api
            dockerfile: Dockerfile.postgres
    
    website:
        build:
            context: ./web
            dockerfile: Dockerfile.django

    worker:
        build:
            context: ./api
            dockerfile: Dockerfile.worker
    beat:
        build:
            context: ./api
            dockerfile: Dockerfile.beat
    redis:
        build:
            context: ./api
            dockerfile: Dockerfile.redis