# tcp:
#   routers:
#     vmq-cluster-router:
#       entrypoints:
#         - mqtts
#       rule: "HostSNI(`vmq-cluster.inditan.com`)"
#           # rule: "HostSNI(`*`)"
#       service: vmq-cluster-service
#       tls:
#         certresolver: myresolver

#   services:
#     vmq-cluster-service:
#       loadBalancer:
#         servers:
#           - address: "ip_address:8883"

http:
  routers:
    {{range $i, $e := until 20 }}
    test{{ $e }}-router:
      entrypoints:
        - websecure
      rule: "Host(`inditan.localhost`) && PathPrefix(`/api/test{{ $e }}/`)"
      service: test{{ $e }}-service
      # tls:
      #   certresolver: myresolver
    {{end}}
    # kosh-data-router:
    #   entrypoints:
    #     - websecure
    #     - web
    #   rule: "Host(`data.getkosh.com`)"
    #   middlewares:
    #     - redirect-to-https
    #     - add-headers-for-data
    #   service: kosh-data-service
    #   tls:
    #     certresolver: myresolver
    # kosh-superset-router:
    #   entrypoints:
    #     - websecure
    #     - web
    #   rule: "Host(`superset.getkosh.com`)"
    #   middlewares:
    #     - redirect-to-https
    #     - add-headers-for-data
    #   service: kosh-superset-service
    #   tls:
    #     certresolver: myresolver
    # kosh-appsmith-router:
    #   entrypoints:
    #     - websecure
    #     - web
    #   rule: "Host(`internal.getkosh.com`)"
    #   middlewares:
    #     - redirect-to-https
    #     - add-headers-for-data
    #   service: kosh-appsmith-service
    #   tls:
    #     certresolver: myresolver
    # kosh-grafana-router:
    #   entrypoints:
    #     - websecure
    #     - web
    #   rule: "Host(`grafana.getkosh.com`)"
    #   middlewares:
    #     - redirect-to-https
    #   service: kosh-grafana-service
    #   tls:
    #     certresolver: myresolver
    # kosh-jenkins-router:
    #   entrypoints:
    #     - websecure
    #     - web
    #   rule: "Host(`jenkins.getkosh.com`)"
    #   middlewares:
    #     - redirect-to-https
    #   service: kosh-jenkins-service
    #   tls:
    #     certresolver: myresolver
    # kosh-sonarqube-router:
    #   entrypoints:
    #     - websecure
    #     - web
    #   rule: "Host(`sonar.getkosh.com`)"
    #   middlewares:
    #     - redirect-to-https
    #   service: kosh-sonar-service
    #   tls:
    #     certresolver: myresolver

  services:
    {{range $i, $e := until 10 }}
    test{{ $e }}-service:
      loadBalancer:
        servers:
          - url: "http://inditan.localhost:800{{ $e }}"
    {{end}}
    {{range $i, $e := untilStep 10 20 1}}
    test{{ $e }}-service:
      loadBalancer:
        servers:
          - url: "http://inditan.localhost:80{{ $e }}"
    {{end}}
    {{range $i, $e := until 10 }}
    # kosh-data-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://15.206.83.131:8089"
    # kosh-superset-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://15.206.83.131:8088"
    # kosh-appsmith-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://15.206.83.131:80"
    # kosh-grafana-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://15.206.83.131:3000"
    # kosh-jenkins-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://3.110.100.130:8080"
    # kosh-sonar-service:
    #   loadBalancer:
    #     servers:
    #       - url: "http://3.110.100.130:9092"

  middlewares:
    redirect-to-https:
      redirectscheme:
        scheme: "https"
    add-headers-for-data:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"