api:
  dashboard: true

log:
  level: ERROR

providers:
  file:
    directory: "/etc/traefik"
  docker:
    exposedbydefault: false

entrypoints:
  web:
    address: ":80"
  websecure:
    address: ":443"